### ISSUE TITLE
Resposta sobre feedback 

### ISSUE THREAD

**Issue by Emanuelmeira** [solutisfsw/desafio-multiverso-chatbot#30]
Olá, Boa tarde, 
Acabo de receber o feedback de que minha interface não funcionou por "algum motivo", se possível,  gostaria de mais detalhes do que aconteceu. A aplicação angular tinha dependências, todas foram baixadas sem problemas ? (com "npm install"), o arquivo .env foi enviado junto com a API em node, mas sem os dados sensíveis do serviço do Watson, os dados foram enviados posteriormente por email. 

Agradeço, desde já, a atenção.

**Comment by solutisfsw** [comment]
Oi Emanuel, boa tarde!
Tanto a instalação quanto a execução das aplicações foram feitas conforme o guia de instalação que foi enviado. Em todos os casos em que a interface do chat não funcionou seguindo o guia, foram feitas novas tentativas com base em uma breve análise do código. Além disso, mesmo que a aplicação não tenha funcionado, o contexto do watson foi verificado através das credenciais (utilizando uma interface default).
Mas isso é apenas um detalhe principalmente porque você captou o espírito do desafio, portanto fique tranquilo e arrebente no hackathon!

Att.,
