### ISSUE TITLE
Feedback desafio

### ISSUE THREAD

**Issue by biancamagalhaes** [solutisfsw/desafio-multiverso-chatbot#32]
Boa noite, 

Recebi o feedback de vocês dizendo que não fiz o que foi pedido e gostaria de explicar minha ideia e de um retorno de vocês o que eu não fiz dentro do proposto. Minha ideia foi criar um empresa que terceriza o trabalho de "soldados" que estão congelados, então fiz um mini site e na aba contrate coloquei o meu chatbot que dá todas as informações necessárias para esse soldado ser contratado. Espero de vocês um retorno e obrigada pela atenção.

Atenciosamente, Bianca Magalhães

**Comment by solutisfsw** [comment]
Oi Bianca, boa tarde!
A criatividade para entregar algo além do proposto também foi parte da avaliação, porém a idéia do desafio era que cada participante falasse um pouco de si de maneira lúdica e utilizando a tecnologia. Com sua proposta de criar uma empresa o "guerreiro" acabou ficando em segundo plano na interface.
Mesmo assim, fique tranquila e utilize suas habilidades para arrebentar no hackathon!
Att.,
