### ISSUE TITLE
feedeback

### ISSUE THREAD

**Issue by gabrieljony** [solutisfsw/desafio-multiverso-chatbot#4]
Olá,

Após fazer o Update dos arquivos no repositório do github e encaminhar o e-mail para Marx, será dado algum feedback sobre o Chatbot realizado? Teremos a confirmação se foi enviado para Marx?

Aguardo um retorno.

Atenciosamente,
Gabriel Jony

**Comment by solutisfsw** [comment]
Olá Gabriel, bom dia!

Todos os candidatos que submeteram seus chatbots para correção receberão feedback sim. 
Só aguardar!

Atenciosamente
