### ISSUE TITLE
Problemas com o pull request

### ISSUE THREAD

**Issue by DaniloDevSouza** [solutisfsw/desafio-multiverso-chatbot#7]
Olá, boa tarde ! 

Fiz o fork do projeto e fiz minhas alterações, estou pronto para enviar, porém não estou conseguindo fazer o pull request, uso a aplicação para desktop.

att.,

**Comment by solutisfsw** [comment]
Olá, bom dia!

Tente fazer novamente o processo de fork e pull request, pois seu fork pode ter sido desconectado do repositório. 
Vale lembrar que o envio da interface é muito importante para a correção e é eliminatório.

Atenciosamente,
